# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86eaa2999597bf555b600264b3cbbe0fac44627c6e1967ca7ccefb8c8e432258b7c9448b9d6b4c3a367149705467de0970be72421db2a361d99d339d483c83a7

test:
  secret_key_base: 78c254aac483ec51dd6a04304eef7f3d08c27091e8de98b29ab86fefeb4f2ab5d638ca3b7515e772725cddbd47f57446393fb3bc3297532f0395d5a16c994d87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
